apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana-release
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: grafana
  chart:
    repository: https://grafana.github.io/helm-charts/
    name: grafana
    version: 6.0.1
  rollback:
    enable: true
    retry: true
    maxRetries: 5  
  maxHistory: 20
  values:
    image:
      repository: grafana/grafana
      tag: 7.3.0
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: public-nginx-ingress
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - grafana.ssbkang.io
      tls:
        - hosts:
          - grafana.ssbkang.io
          secretName: tls-secret
    nodeSelector:
      beta.kubernetes.io/os: linux
    envRenderSecret:
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP : "true"
      GF_AUTH_GENERIC_OAUTH_ALLOWED_ORGANIZATIONS : ""
      GF_AUTH_GENERIC_OAUTH_API_URL : ""
      GF_AUTH_GENERIC_OAUTH_AUTH_URL : "https://login.microsoftonline.com/xxx/oauth2/v2.0/authorize"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID : "xxx"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET : "xxx"
      GF_AUTH_GENERIC_OAUTH_ENABLED : "true"
      GF_AUTH_GENERIC_OAUTH_NAME : "Azure AD"
      GF_AUTH_GENERIC_OAUTH_SCOPES : "openid email profile"
      GF_AUTH_GENERIC_OAUTH_TEAM_IDS : ""
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL : "https://login.microsoftonline.com/xxx/oauth2/v2.0/token"
      GF_INSTALL_PLUGINS : "grafana-clock-panel,grafana-simple-json-datasource,grafana-azure-monitor-datasource,briangann-gauge-panel"
      GF_SERVER_ROOT_URL : "https://grafana.ssbkang.io"
      GF_SMTP_ENABLED : "false"
      GF_SMTP_FROM_ADDRESS : ""
      GF_SMTP_HOST : ""
      GF_SMTP_PASSWORD : ""
      GF_SMTP_SKIP_VERIFY : "false"
      GF_SMTP_USER : ""
      GF_DATABASE_URL : "sqlite3:///var/lib/grafana/grafana.db?cache:private&mode:rwc&_journal_mode:WAL"
    persistence:
      type: pvc
      enabled: true
      finalizers:
        - kubernetes.io/pvc-protection
      existingClaim: grafana-pvc
