apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus
    version: 11.12.1
  rollback:
    enable: true
    retry: true
    maxRetries: 5  
  maxHistory: 20
  values:
    alertmanager:
      enabled: false
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
      nodeSelector:
        beta.kubernetes.io/os: linux
    pushgateway:
      enabled: false
    server:
      image:
        repository: prom/prometheus
        tag: v2.22.0
      nodeSelector:
        beta.kubernetes.io/os: linux
      persistentVolume:
        enabled: true
        existingClaim: "prometheus-pvc"
        mountPath: /data